'use client';
import { useState } from 'react';
import { builtStudies } from '../studyData';
import { PhoneFrame, StudyFrame } from '../_components/StudyFrame';
const study = builtStudies.find(s => s.slug === 'compare-trust')!;
const variants = {
  Classic: { type:'Classic / sacred / old text', original:'In the beginning God created the heaven and the earth. And the earth was without form, and void; and darkness was upon the face of the deep.', understand:'Before there was land beneath anyone’s feet, before there was morning or sky, the world rested in a deep and quiet dark. Everything was waiting to be shaped.', default:'Toggle + optional notes' },
  Legal: { type:'Legal / high-trust text', original:'You agree that the licensed application is licensed, not sold, under the terms of this agreement.', understand:'You can use the app under the agreement, but you do not own it.', default:'Side-by-side + notes' },
  Casual: { type:'Casual / low-risk text', original:'The article is long, dry, and full of jargon about zoning incentives.', understand:'This article explains why zoning incentives matter, but it buries the useful point in technical language.', default:'Toggle only' },
} as const;
const notes = [['Preserved claim', 'The retelling keeps the main claim and changes wording for oral comprehension.'],['Changed metaphor', 'Imagery is modernized only when the chosen style/fidelity allows it.'],['Added connective tissue', 'Small transitions may be added so the passage makes sense when heard.'],['Compressed detail', 'Some detail may be compressed in freer modes; high-trust text needs clearer disclosure.']];
export default function Page(){
  const [view,setView]=useState<'toggle'|'side'|'notes'>('toggle'); const [mode,setMode]=useState<'Original'|'Understand'>('Understand'); const [variant,setVariant]=useState<keyof typeof variants>('Classic'); const item=variants[variant];
  return <StudyFrame study={study}><section className="us-demo"><PhoneFrame label="Trust comparison"><h3>Can I trust this?</h3><p className="us-mini">Text type: {item.type}. Suggested default: {item.default}.</p><div className="us-chip-row">{Object.keys(variants).map(v=><button key={v} className={variant===v?'active':''} onClick={()=>setVariant(v as keyof typeof variants)}>{v}</button>)}</div><div className="us-chip-row"><button className={view==='toggle'?'active':''} onClick={()=>setView('toggle')}>Toggle</button><button className={view==='side'?'active':''} onClick={()=>setView('side')}>Side-by-side</button><button className={view==='notes'?'active':''} onClick={()=>setView('notes')}>Change notes</button></div>{view==='toggle' && <><div className="us-tabs"><button className={mode==='Original'?'active':''} onClick={()=>setMode('Original')}>Original</button><button className={mode==='Understand'?'active':''} onClick={()=>setMode('Understand')}>Understand</button></div><div className="us-preview">{mode==='Original'?item.original:item.understand}</div></>}{view==='side' && <div className="us-compare"><div><strong>Original</strong><br/>{item.original}</div><div><strong>Understand</strong><br/>{item.understand}</div></div>}{view==='notes' && <div className="us-preview">{notes.map(([a,b])=><p key={a}><strong>{a}</strong><br/><span className="us-mini">{b}</span></p>)}</div>}<button className="us-primary">Play trusted retelling</button></PhoneFrame><aside className="us-side-panel"><div className="us-state-card"><h3>Trust ≠ study mode</h3><p>The goal is quick confidence before listening. Deep annotation should be contextual, not the default app personality.</p></div><div className="us-state-card"><h3>Default recommendation</h3><p>Use Original/Understand toggle by default. Offer side-by-side or notes for legal, medical, academic, sacred, or unusually transformed text.</p></div><div className="us-state-card"><h3>Failure mode</h3><p>If every passage opens in diff mode, the app becomes homework and loses the listening promise.</p></div></aside></section></StudyFrame>
}
