import Link from 'next/link';

const decisions = [
  {status:'Recommendation', item:'Persona / Choose the Retelling Style and Closeness', reason:'This is the clearest model for separating medium from source-distance.', evidence:'/labs/understand/studies/retelling-style-fidelity'},
  {status:'Recommendation', item:'Text-first IA', reason:'Passage is the strongest root object for first open and active use.', evidence:'/labs/understand/studies/passage-stage'},
  {status:'Needs decision', item:'Check the Retelling Against the Original level', reason:'We need to decide toggle-only, side-by-side, or contextual notes by text type.', evidence:'/labs/understand/studies/compare-trust'},
  {status:'Recommendation', item:'Sample-first aha', reason:'Proof passages teach the promise before paste/import friction.', evidence:'/labs/understand/studies/sample-aha'},
  {status:'Needs verification', item:'Premium as expressive performance', reason:'Strong business story, but copy must stay truthful about actual model capability.', evidence:'/labs/understand/studies/performance-capability'},
  {status:'Defer depth', item:'Continue / Library', reason:'Useful for retention, but lower priority until the first-session loop is strong.', evidence:'/labs/understand/studies/continue-loop'},
  {status:'Candidate only', item:'Coach / Narrator / Workflow-first', reason:'Potentially useful later, but each risks reframing the product away from the core promise.', evidence:'/labs/understand/studies'},
];
const questions = ['Which Fidelity labels are clearest: Close / Clear / Retold / Freer or another set?', 'What is the default trust affordance by text type?', 'Which TTS providers/voices can actually follow style directions?', 'Which proof samples create the fastest “I want this for my text” reaction?', 'When should share/tester/upgrade asks appear after aha?'];

export const metadata = { title: 'Understand Study Decision Log | Nice Right Labs', robots: { index: false, follow: false } };

export default function DecisionLog(){
  return <main className="us-page"><div className="us-shell"><Link className="us-back" href="/labs/understand/studies">← Studies index</Link><section className="us-hero"><p className="us-eyebrow">Review artifact</p><h1>Decision Log</h1><p className="us-lede">This page separates recommendations from actual decisions. The studies are only useful if they help us decide what graduates into the real app and what stays deferred.</p></section><section className="us-section us-card"><h2>How to use this log</h2><p>Review the evidence page first, then mark the model as Adopt, Iterate, Combine, Reject, or Defer. Do not treat “likely adopt” as decided until the study has been reviewed against the product goal.</p></section><section className="us-section"><h2>Current recommendations and decisions to review</h2><div className="us-grid">{decisions.map(d=><article className="us-study-card" key={d.item}><span className="us-badge">{d.status}</span><h3>{d.item}</h3><p>{d.reason}</p><Link href={d.evidence}>Review evidence →</Link></article>)}</div></section><section className="us-section us-card"><h2>Open questions</h2><ul>{questions.map(q=><li key={q}>{q}</li>)}</ul></section><section className="us-section us-card"><h2>Review protocol</h2><ol><li>Open the composed flow and decide if the full story holds together.</li><li>Open Choose the Retelling Style and Closeness and Check the Retelling Against the Original before judging the app IA.</li><li>Mark each model Adopt / Iterate / Combine / Reject / Defer.</li><li>Only after decisions, create Flutter implementation tasks.</li></ol></section></div></main>
}
