'use client';
import { useState } from 'react';
import { builtStudies } from '../studyData';
import { PhoneFrame, StudyFrame } from '../_components/StudyFrame';
const study = builtStudies.find(s => s.slug === 'continue-loop')!;
const sessions = [
 {title:'Genesis 1', progress:68, status:'unfinished', detail:'Bedtime storyteller · Retold · 1:12 left'},
 {title:'Terms of Service', progress:34, status:'unfinished', detail:'Lawyer · Close · 4:30 left'},
 {title:'Oncology abstract', progress:100, status:'completed', detail:'NPR explainer · Clear · ready to replay/share'},
];
export default function Page(){const [active,setActive]=useState(sessions[0]); return <StudyFrame study={study}><section className="us-section us-card"><h2>Return jobs</h2><div className="us-compare"><div><strong>Continue</strong><br/>Resume something unfinished. This is active, time-based, and action-oriented.</div><div><strong>Library</strong><br/>Retrieve something saved or completed. This is secondary storage, not first-run navigation.</div></div></section><section className="us-demo"><PhoneFrame label="Continue loop"><h3>Continue understanding</h3><p className="us-mini">Not history. A resume surface for returning users.</p><div className="us-preview"><strong>{active.title}</strong><p>{active.detail}</p><div className="us-progress"><span style={{width:`${active.progress}%`}} /></div><p className="us-mini">{active.progress}% complete · {active.status}</p><button className="us-primary">{active.progress===100?'Replay':'Resume'}</button>{active.progress===100 && <button className="us-secondary">Share completed retelling</button>}</div><p className="us-mini">Library</p>{sessions.map(s=><button key={s.title} className="us-secondary" onClick={()=>setActive(s)} style={{margin:'4px'}}>{s.title}</button>)}</PhoneFrame><aside className="us-side-panel"><div className="us-state-card"><h3>Priority note</h3><p>This is valuable, but it should not outrank first-session aha. You only need Continue after something is worth continuing.</p></div><div className="us-state-card"><h3>PLG</h3><p>Retention precedes referral: continued sessions produce completed retellings worth sharing later.</p></div></aside></section></StudyFrame>}
