'use client';
import { useState } from 'react';
import { builtStudies } from '../studyData';
import { PhoneFrame, StudyFrame } from '../_components/StudyFrame';
const study = builtStudies.find(s => s.slug === 'sample-aha')!;
const cards = [
 {name:'Genesis', job:'Old / sacred / beautiful text', why:'Proves archaic language can become listenable without cheapening the source.', proof:'Old text becomes story-like', recipe:'Biblical storyteller · Retold', before:'And darkness was upon the face of the deep.', after:'The world rested in deep darkness, waiting for light.'},
 {name:'Shakespeare', job:'Classic / literary text', why:'Proves famous text can become clear enough to hear without losing dramatic stakes.', proof:'Classic drama becomes listenable', recipe:'NPR explainer · Clear', before:'To be, or not to be, that is the question.', after:'He is asking whether it is better to keep living through pain or end it.'},
 {name:'Legalese', job:'Annoying / practical dense text', why:'Proves the app is useful for real obligations, not only beautiful old passages.', proof:'Dense rules become plain stakes', recipe:'Lawyer · Close', before:'Licensed, not sold, under this agreement.', after:'You can use it, but you do not own it.'},
 {name:'Aesop', job:'Short story / childlike moral text', why:'Proves the retelling can preserve narrative shape and make listening easy.', proof:'Story becomes instantly graspable', recipe:'Bedtime storyteller · Clear', before:'A crow, half-dead with thirst, came upon a pitcher.', after:'A thirsty crow finds water just out of reach and has to get clever.'},
];
export default function Page(){const [active,setActive]=useState(cards[0]); return <StudyFrame study={study}><section className="us-section us-card"><h2>Sample selection criteria</h2><p>Samples should not be random demo content. Each should prove one job: old/archaic, dense/professional, annoying/legal, literary/classic, or emotionally useful everyday text.</p><div className="us-principle-grid"><div><strong>Try sample</strong><br/>Low effort.</div><div><strong>Aha</strong><br/>Hear the transformation.</div><div><strong>Paste own</strong><br/>Apply to personal text.</div><div><strong>Share/save</strong><br/>Only after value.</div></div></section><section className="us-demo"><PhoneFrame label="Sample aha"><h3>Hear the difference</h3><p className="us-mini">Samples are curated proof passages, not filler.</p><div className="us-chip-row">{cards.map(c=><button key={c.name} className={c.name===active.name?'active':''} onClick={()=>setActive(c)}>{c.name}</button>)}</div><div className="us-preview"><strong>{active.proof}</strong><p className="us-mini">{active.recipe}</p><p><strong>Why this sample:</strong> {active.why}</p><div className="us-compare"><div><strong>Original</strong><br/>{active.before}</div><div><strong>Understand</strong><br/>{active.after}</div></div></div><button className="us-primary">Play sample</button><button className="us-secondary">Paste my own</button></PhoneFrame><aside className="us-side-panel"><div className="us-state-card"><h3>What this tests</h3><p>Does the sample make the user want to try their own text before we explain the whole product?</p></div><div className="us-state-card"><h3>PLG loop</h3><p>Try sample → aha → paste own → save/share. Growth starts from a useful artifact.</p></div></aside></section></StudyFrame>}
